charset: utf-8
locale: en_US

title: After the Beep
number: '+14426672337'
owner: the operator
email: operator@afterthebeep.tel

source_repo: https://gitlab.com/unixispower/after-the-beep

api_url: https://api.blaines.world
neocities: afterthebeep
