#!/bin/sh
# Build and upload a site to Neocities
CONFIG_FILE=_utils/upload.conf

. "$CONFIG_FILE"

jekyll build

# upload index last to ensure resources are available
export NEOCITIES_API_KEY
neocities push -e index.html "$SITE_DIR"
neocities upload "$SITE_DIR/index.html"
